from AI_NON_INTELLIGENT.Player import MaxNPlayer as Player
from AI_NON_INTELLIGENT.Player import QLearningPlayer
from AI_NON_INTELLIGENT.Player import GreedyPlayer
from AI_NON_INTELLIGENT.Player import AlternativeGreedyPlayer